TestDapper/Controllers/AutoController.cs
using TestDapper.DbContext;
using TestDapper.Models;
using TestDapper.Repository;

namespace TestDapper.Controllers;

#region Old Controller Auto (works)
//public class AutoController : Controller
//{

//    const string connectionString = "User ID=postgres;Password=admin!@#;Host=localhost;Port=5432;Database=testbase;";
//    public IActionResult Index()
//    {
//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string favotireQuery = "SELECT * FROM auto";
//            connection.Open();
//            IEnumerable<Auto> ListCars = connection.Query<Auto>(favotireQuery).ToList();
//            return View(ListCars);
//        }

//    }

//    [HttpGet]
//    public IActionResult Create()
//    {

//        return View();
//    }

//    [HttpPost]
//    public IActionResult Create(Auto auto)
//    {
//        if (ModelState.IsValid)
//        {
//            IDbConnection connection;

//            using (connection = new NpgsqlConnection(connectionString))
//            {
//                string insertQuery = "INSERT INTO auto(brand,model) VALUES(@brand, @model)";

//                connection.Open();
//                connection.Execute(insertQuery, auto);
//                connection.Close();
//                return RedirectToAction(nameof(Index));
//            }

//        }
//        return View(auto);
//    }

//    [HttpGet]
//    public IActionResult Edit(int? id)
//    {

//        if (id == null)
//        {
//            return NotFound();
//        }

//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string favoriteQuery = "SELECT * FROM auto WHERE id = @id";
//            connection.Open();
//            Auto auto = connection.Query<Auto>(favoriteQuery, new { id = id }).FirstOrDefault();
//            connection.Close();
//            return View(auto);
//        }
//    }

//    [HttpPost]
//    public IActionResult Edit(int id, Auto auto)
//    {
//        if (id != auto.Id)
//        {
//            return NotFound();
//        }

//        if (ModelState.IsValid)
//        {

//            IDbConnection connection;

//            using (connection = new NpgsqlConnection(connectionString))
//            {
//                string updateQuery = "UPDATE auto SET brand=@brand, model=@model WHERE id=@id";
//                connection.Open();
//                connection.Execute(updateQuery, auto);
//                connection.Close();
//                return RedirectToAction(nameof(Index));
//            }
//        }

//        return View(auto);
//    }

//    [HttpPost]
//    public IActionResult Delete(int id)
//    {
//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string deleteQuery = "DELETE FROM auto WHERE id=@id";
//            connection = new NpgsqlConnection();
//            connection.Open();
//            connection.Execute(deleteQuery, new { id = id });
//            connection.Close();
//            return RedirectToAction(nameof(Index));
//        }

//    }
//}
#endregion

#region Api controller

//public class AutoController : Controller
//{
//    private readonly IAutoRepository _autoRepository;

//    public AutoController(IAutoRepository autoRepository, IAdditionalDbOperations additionalDbOperations)
//    {
//        _autoRepository = autoRepository;

//        additionalDbOperations.CreateTableIfNotExists().GetAwaiter().GetResult();
//        additionalDbOperations.GetVersion().GetAwaiter().GetResult();
//    }

//    // GET: api/<AutoController>
//    [HttpGet]
//    public async Task<ActionResult<IEnumerable<Auto>>> Get()
//    {
//        var allAuto = await _autoRepository.GetCars();
//        return Ok(allAuto);
//    }

//    // GET api/<AutoController>/5
//    [HttpGet("{id}")]
//    public async Task<ActionResult<Auto>> GetCar(int id)
//    {
//        var auto = await _autoRepository.GetCar(id);
//        if (auto != null)
//            return Ok(auto);
//        else
//            return NotFound();
//    }

//    // POST api/<AutoController>
//    [HttpPost]
//    public async Task<ActionResult> CreateCar([FromBody] Auto auto)
//    {
//        await _autoRepository.CreateCar(auto);
//        return Ok();
//    }

//    // PUT api/<AutoController>/5
//    [HttpPut("{id}")]
//    public async Task<ActionResult> UpdateCar(int id, [FromBody] Auto auto)
//    {
//        await _autoRepository.UpdateCar(id, auto);
//        return Ok();
//    }

//    // DELETE api/<AutoController>/5
//    [HttpDelete("{id}")]
//    public async Task<ActionResult> DeleteCar(int id)
//    {
//        await _autoRepository.DeleteCar(id);
//        return Ok();
//    }
//}
#endregion

#region New Controller (works)
public class AutoController : Controller
{
    private readonly IAutoRepository _autoRepository;

    public AutoController(IAutoRepository autoRepository)
    {
        this._autoRepository = autoRepository;
    }

    [HttpGet]
    // GET: AutoController
    public async Task<IActionResult> Index()
    {
        try
        {
            var cars = await _autoRepository.GetCars();
            return View(cars);
        }
        catch (Exception ex)
        {
            // Log error
            return StatusCode(500, ex.Message);
        }


    }

    [HttpGet]
    // GET: AutoController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: AutoController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(Auto auto)
    {
        if (ModelState.IsValid)
        {
            await _autoRepository.CreateCar(auto);
            return RedirectToAction(nameof(Index));
        }

        return View(auto);
    }

    [HttpGet]
    // GET: AutoController/Edit/5
    public async Task<ActionResult> Edit(int? id)
    {
        if (id == null)
        {
          return NotFound();
        }

        var car = await _autoRepository.GetCar(id);
        return View(car);
    }

    // POST: AutoController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, Auto auto)
    {
        if (id != auto.Id)
        {
           return NotFound();
        }

        if (ModelState.IsValid)
        {
            await _autoRepository.UpdateCar(id, auto);
            return RedirectToAction(nameof(Index));
        }
        return View();
        
    }

    // POST: AutoController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Delete(int id)
    {
        try
        {
            await _autoRepository.DeleteCar(id);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

#endregion

TestDapper/Controllers/DriverController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System.Configuration;
using TestDapper.DbContext;
using TestDapper.Models;
using TestDapper.Repository;

namespace TestDapper.Controllers;
#region Old controller Driver (works)
//public class DriverController : Controller
//{

//    const string connectionString = "User ID=postgres;Password=admin!@#;Host=localhost;Port=5432;Database=testbase;";
//    public IActionResult Index()
//    {
//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string favotireQuery = "SELECT * FROM driver";

//            connection.Open();
//            IEnumerable<Driver> ListDriver = connection.Query<Driver>(favotireQuery).ToList();
//            return View(ListDriver);
//        }
//    }

//    [HttpGet]
//    public IActionResult Create()
//    {

//        return View();
//    }

//    [HttpPost]
//    public IActionResult Create(Driver driver)
//    {
//        if (ModelState.IsValid)
//        {
//            IDbConnection connection;

//            using (connection = new NpgsqlConnection(connectionString))
//            {
//                string insertQuery = "INSERT INTO driver(name) VALUES(@name)";
//                connection = new NpgsqlConnection(connectionString);
//                connection.Open();
//                connection.Execute(insertQuery, driver);
//                connection.Close();
//                return RedirectToAction(nameof(Index));
//            }

//        }
//        return View(driver);
//    }

//    [HttpGet]
//    public IActionResult Edit(int id)
//    {
//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string favoriteQuery = "SELECT * FROM driver WHERE id = @id";
//            connection = new NpgsqlConnection(connectionString);
//            connection.Open();
//            Driver driver = connection.Query<Driver>(favoriteQuery, new { id = id }).FirstOrDefault();
//            connection.Close();
//            return View(driver);
//        }
//    }

//    [HttpPost]
//    public IActionResult Edit(int id, Driver driver)
//    {
//        if (id != driver.Id)
//        {
//            return NotFound();
//        }

//        if (ModelState.IsValid)
//        {

//            IDbConnection connection;

//            using (connection = new NpgsqlConnection(connectionString))
//            {
//                string updateQuery = "UPDATE driver SET name=@name WHERE id=@id";
//                connection.Open();
//                connection.Execute(updateQuery, driver);
//                connection.Close();
//                return RedirectToAction(nameof(Index));
//            }
//        }

//        return View(driver);
//    }

//    [HttpPost]

//    public IActionResult Delete(int id)
//    {
//        IDbConnection connection;

//        using (connection = new NpgsqlConnection(connectionString))
//        {
//            string deleteQuery = "DELETE FROM driver WHERE id = @id";
//            connection.Open();
//            connection.Execute(deleteQuery, new { id = id });
//            connection.Close();
//            return RedirectToAction(nameof(Index));
//        }
//    }
//}
#endregion

#region DriverApiController

//public class DriverController : Controller
//{
//    private readonly IDriverRepository _driverRepository;

//    public DriverController(IDriverRepository driverRepository, IAdditionalDbOperations additionalDbOperations)
//    {
//        _driverRepository = driverRepository;

//        additionalDbOperations.CreateTableIfNotExists().GetAwaiter().GetResult();
//        additionalDbOperations.GetVersion().GetAwaiter().GetResult();
//    }

//    // GET: api/<DriverController>
//    [HttpGet]
//    public async Task<ActionResult<IEnumerable<Driver>>> GetDriver()
//    {
//        var allDrivers = await _driverRepository.GetDrivers();
//        return Ok(allDrivers);
//    }

//    // GET api/<DriverController>/5
//    [HttpGet("{id}")]
//    public async Task<ActionResult<Driver>> GetDriver(int id)
//    {
//        var driver = await _driverRepository.GetDriver(id);
//        if (driver != null)
//            return Ok(driver);
//        else
//            return NotFound();
//    }

//    // POST api/<DriverController>
//    [HttpPost]
//    public async Task<ActionResult> CreateDriver([FromBody] Driver driver)
//    {
//        await _driverRepository.CreateDriver(driver);
//        return Ok();
//    }

//    // PUT api/<DriverController>/5
//    [HttpPut("{id}")]
//    public async Task<ActionResult> UpdateDriver(int id, [FromBody] Driver driver)
//    {
//        await _driverRepository.UpdateDriver(id, driver);
//        return Ok();
//    }

//    // DELETE api/<DriverController>/5
//    [HttpDelete("{id}")]
//    public async Task<ActionResult> DeleteDriver(int id)
//    {
//        await _driverRepository.DeleteDriver(id);
//        return Ok();
//    }
//}

#endregion

#region New controller (works)
public class DriverController : Controller
{
    private readonly IDriverRepository _driverRepository;

    public DriverController(IDriverRepository driverRepository)
    {
        this._driverRepository = driverRepository;
    }

    [HttpGet]
    // GET: DriverController
    public async Task<IActionResult> Index()
    {
        try
        {
            var drivers = await _driverRepository.GetDrivers();
            return View(drivers);
        }
        catch (Exception ex)
        {
            // Log error
            return StatusCode(500, ex.Message);
        }


    }

    //[HttpGet]
    //public JsonResult GetDriversAutosMultipleResults(int id)
    //{

    //    var cars = _driverRepository.GetDriversAutosMultipleResults(id);
    //    return Json(cars);

    //}


    [HttpGet]
    public async Task<JsonResult> GetDriversAutosMultipleMappingAsync()
    {
        ViewBag.Cars = GetDriversAutosMultipleMappingAsync();
        var cars = await _driverRepository.GetDriversAutosMultipleMapping();
        return Json(cars);

    }

    [HttpGet]
    // GET: DriverController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: DriverController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(Driver driver)
    {

        if (ModelState.IsValid)
        {
            await _driverRepository.CreateDriver(driver);
            return RedirectToAction(nameof(Index));
        }

        return View(driver);
    }

    [HttpGet]
    // GET: DriverController/Edit/5
    public async Task<ActionResult> Edit(int? id)
    {

        if (id == null)
        {
            return NotFound();
        }

        var driver = await _driverRepository.GetDriver(id);
        return View(driver);
    }

    // POST: DriverController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, Driver driver)
    {
        if (id != driver.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            await _driverRepository.UpdateDriver(id, driver);
            return RedirectToAction(nameof(Index));
        }
        return View();
    }

    // POST: DriverController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Delete(int id)
    {
        try
        {
            await _driverRepository.DeleteDriver(id);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}
#endregion

TestDapper/Controllers/HomeController.cs
using TestDapper.Models;

namespace TestDapper.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TestDapper/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>Main</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <style>
        .card {
            border-radius: 1em;
            text-align: center;
            padding: 1em;
        }

            .card:hover {
                background-color: rgba(0, 0, 0, 0.1)
            }

            .card img {
                border-radius: 50%;
                width: 60%;
                margin: auto;
            }
    </style>
</head>
<body>
    <div class="container text-center my-5">
        <div class="row" row-cols-1 row-cols-md-2 row-cols-lg-3 g-5>
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card">
                    <div class="card-image">
                        <img src="https://picsum.photos/id/111/800">
                        <span class="card-title">Drivers</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Just check drivers
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Driver" asp-action="Index" target="_blank" class="btn btn-primary">Check</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card">
                    <div class="card-image">
                        <img src="https://picsum.photos/id/376/800">
                        <span class="card-title">Cars</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Just check cars
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Auto" asp-action="Index" target="_blank" class="btn btn-primary">Check</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*<div class="section no-pad-bot" id="index-banner">
    <div class="container">
    <br><br>
    <h1 class="header center orange-text">Example</h1>
    <div class="row center">
    <h5 class="header col s12 light">Drivers and Cars</h5>
    </div>
    <div class="row center">
    <!-- Dropdown Trigger -->
    <a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Drop Me!</a>

    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider" tabindex="-1"></li>
    <li><a href="#!">three</a></li>
    <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
    <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
    </ul>
    </div>
    <br><br>

    </div>
    </div>*@

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="js/materialize.js"></script>
    <script src="js/init.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>$('.dropdown-trigger').dropdown();</script>
</body>
</html>